DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS orders;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  -- id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR(256) NOT NULL,
  zipcode VARCHAR(256) NOT NULL,
  quote VARCHAR(256) NOT NULL,
  park VARCHAR(256) NOT NULL
)